language: python
python:
  - "2.7"
  - "3.5"

sudo: false

addons:
  apt:
    packages:
      - vim

branches:
  only:
    - master
    - travis

install:
  # Install vim plugins
  - curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  - vim -u .travis/vimrc +PlugInstall +qall

script:
  - vim --version
  - ./vim-profiler.py vim -u NONE
  - ./vim-profiler.py vim -u .travis/vimrc
  - ./vim-profiler.py -n 5 vim -u .travis/vimrc
  - ./vim-profiler.py -n 5 -r 10 vim -u .travis/vimrc
  - ./vim-profiler.py -s vim -N -u NORC
