language: r
r:
  - release
  - devel

branches:
  only:
  - master
  - develop

sudo: false

addons:
  apt:
    packages:
      - vim
      - ruby
      - r-base 
      - r-base-dev
      - python-matplotlib
      - python3-matplotlib

branches:
  only:
    - master
    - travis

install:
  # Install vim plugins
  - curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  - cp .travis/vimrc ~/.vimrc
  - vim -u ~/.vimrc +PlugInstall +qall
 
before_script:
  - mkdir -p ~/R/library
  - export R_LIBS_USER="~/R/library/"

script:
  - vim --version
  - python --version
  - ruby --version
  - R --version
  - python ./vim-plugins-profile.py vim -u NONE
  - python ./vim-plugins-profile.py vim -u .travis/vimrc
  - python ./vim-plugins-profile.py -n 5 vim -u .travis/vimrc
  - python ./vim-plugins-profile.py -n 5 -r 10 vim -u .travis/vimrc
  - python ./vim-plugins-profile.py -s vim -N -u NORC
  - ruby ./vim-plugins-profile.rb
  - yes | bash vim-plugins-profile.sh
  - find ~/R/
  - ls -laR ~/R/
